---
title: "Country spending too much or too little on defense data and Investment spending"
author: "src"
date: "October 16, 2015"
output: html_document
---

**Load packages and support files**
```{r Setup, echo = FALSE, results = "hide"}
options(error=recover)
options(warn=1)

require(Hmisc)
require(texreg)
require(plm)
require(ggplot2)
require(reshape)
require(plyr)
require(quantmod)

#Your working directory here!
# setwd("K:/Development/Europe") #Your working directory here!
#setwd("C:/Users/Greg Sanders/Documents/Development/Europe")
# setwd("C:/Users/scohen/My Documents/Europe/Git/Europe")

source("EuropeInput.R")

```


**Load and subset the data we want**
```{r Input, echo = FALSE, results = "hide"}


#debug(CompilePubOpDataOmnibus)
##load data using function
#undebug(CompilePubOpDataOmnibus)
EuropeOmnibus <- CompilePubOpDataOmnibus()


write.table(EuropeOmnibus
            ,file=paste("data\\EuropeOmnibus.csv"
                        ,sep=""
                        )
            #   ,header=TRUE
            , sep=","
            , row.names=FALSE
            , append=FALSE
            )


#get rid of greece
EuropeOmnibus <- subset(EuropeOmnibus, !Country %in% c("Greece", "Sweden","Russia","United States"))

##get rird of 2002 and 2003
# EuropeOmnibus <- subset(EuropeOmnibus, !Year %in% c("2002"))


write.table(EuropeOmnibus
            ,file=paste("data\\EuropeSample.csv"
                        ,sep=""
                        )
            #   ,header=TRUE
            , sep=","
            , row.names=FALSE
            , append=FALSE
            )
##change government spreads from factors



```


**load and subset the data we want**
```{r DefSpreadNarrowing, echo = FALSE, results = "hide"}

##load data using function
EuropeDefSpread <- subset(EuropeOmnibus, !is.na(DefSpendDelt_lead))


##get rid of sweden
EuropeDefSpread <- subset(EuropeDefSpread, !Country %in% c("Sweden", "Serbia", "Bulgaria", "Romania"))

# EuropeDefSpread <- subset(EuropeDefSpread, Year>2002)


EuropeDefSpread_lag0 <- subset(EuropeDefSpread, !is.na(DefSpread))
EuropeDefSpread_lag1 <- subset(EuropeDefSpread, !is.na(DefSpread_lag1))
EuropeDefSpread_lag2 <- subset(EuropeDefSpread, !is.na(DefSpread_lag2))



```


**OLS model adding each variable individually**
```{r EquSpreadOLS, echo = TRUE}
EquEUDefSpreadResults1 <- lm(EquSpendDelt ~ DefSpread, EuropeDefSpread_lag0) 
summary(EquEUDefSpreadResults1)

EquEUDefSpreadResults2 <- lm(EquSpendDelt ~ DefSpread_lag1, EuropeDefSpread_lag1) 
summary(EquEUDefSpreadResults2)
screenreg(list(EquEUDefSpreadResults1,EquEUDefSpreadResults2),
          custom.model.names=c("PubOp_df1","PubOp_df2"))

EquEUDefSpreadResults3 <- lm(EquSpendDelt ~ DefSpread_lag2, EuropeDefSpread_lag2) 
summary(EquEUDefSpreadResults3)
screenreg(list(EquEUDefSpreadResults1,EquEUDefSpreadResults2, EquEUDefSpreadResults3),
          custom.model.names=c("PubOp_df1","PubOp_df2", "PubOp_df3"))

##use 2 lag

EquEUDefSpreadResults4 <- lm(EquSpendDelt ~ DefSpread_lag2 + IntAt, EuropeDefSpread_lag2) 
summary(EquEUDefSpreadResults4)
screenreg(list(EquEUDefSpreadResults1,EquEUDefSpreadResults2, EquEUDefSpreadResults3, EquEUDefSpreadResults4),
          custom.model.names=c("PubOp_df1","PubOp_df2", "PubOp_df3", "IntAt"))

#intAT not significant won't include

EquEUDefSpreadResults5 <- lm(EquSpendDelt ~ DefSpread_lag2 + CivilWar, EuropeDefSpread_lag2) 
summary(EquEUDefSpreadResults5)
screenreg(list(EquEUDefSpreadResults1,EquEUDefSpreadResults2, EquEUDefSpreadResults3, EquEUDefSpreadResults5),
          custom.model.names=c("PubOp_df1","PubOp_df2", "PubOp_df3", "CivilWar"))

##civilwar isn't significant, won't include


EquEUDefSpreadResults6 <- lm(EquSpendDelt ~ DefSpread_lag2 + IntlCnf, EuropeDefSpread_lag2) 
summary(EquEUDefSpreadResults6)
screenreg(list(EquEUDefSpreadResults1,EquEUDefSpreadResults2, EquEUDefSpreadResults3, EquEUDefSpreadResults6),
          custom.model.names=c("PubOp_df1","PubOp_df2", "PubOp_df3", "IntCnf"))

## IntCnf not significant won't include


EquEUDefSpreadResults7 <- lm(EquSpendDelt ~ DefSpread_lag2 + GDPpCapDelt, EuropeDefSpread_lag2) 
summary(EquEUDefSpreadResults7)
screenreg(list(EquEUDefSpreadResults1,EquEUDefSpreadResults2, EquEUDefSpreadResults3, EquEUDefSpreadResults7),
          custom.model.names=c("PubOp_df1","PubOp_df2", "PubOp_df3", "GDPpc"))

##GDP doesn't increase r^2 by more htan .02 points and is statistically significant, will be includee 

EquEUDefSpreadResults8 <- lm(EquSpendDelt ~ DefSpread_lag2 + GDPpCapDelt + Cab_left_right, EuropeDefSpread_lag2) 
summary(EquEUDefSpreadResults8)
screenreg(list(EquEUDefSpreadResults1,EquEUDefSpreadResults2, EquEUDefSpreadResults3, EquiEULeadershipResults7, EquEUDefSpreadResults8),
          custom.model.names=c("PubOp_df1","PubOp_df2", "PubOp_df3", "GDPpCap", "Cableftright"))

##cableft right not significant will not include

EquEUDefSpreadResults9 <- lm(EquSpendDelt ~ DefSpread_lag2 + GDPpCapDelt + Cab_liberty_authority, EuropeDefSpread_lag2) 
summary(EquEUDefSpreadResults9)
screenreg(list(EquEUDefSpreadResults1,EquEUDefSpreadResults2, EquEUDefSpreadResults3, EquiEULeadershipResults7, EquEUDefSpreadResults9),
          custom.model.names=c("PubOp_df1","PubOp_df2", "PubOp_df3","GDPpCapDelt", "lib_authority"))

##cab liberty authority not significant won't be included

EquEUDefSpreadResults10 <- lm(EquSpendDelt ~ DefSpread_lag2 + GDPpCapDelt + Cab_eu_anti_pro, EuropeDefSpread_lag2) 
summary(EquEUDefSpreadResults10)
screenreg(list(EquEUDefSpreadResults1,EquEUDefSpreadResults2, EquEUDefSpreadResults3, EquiEULeadershipResults7, EquEUDefSpreadResults10),
          custom.model.names=c("PubOp_df1","PubOp_df2", "PubOp_df3", "GDPpCap", "euAntiPro"))

##not significant, won't be included eu anti pro

EquEUDefSpreadResults11 <- lm(EquSpendDelt ~ DefSpread_lag2 + GDPpCapDelt + left_right_ls_spread, EuropeDefSpread_lag2) 
summary(EquEUDefSpreadResults11)
screenreg(list(EquEUDefSpreadResults1,EquEUDefSpreadResults2, EquEUDefSpreadResults3, EquEUDefSpreadResults7, EquEUDefSpreadResults11),
          custom.model.names=c("PubOp_df1","PubOp_df2", "PubOp_df3", "GDP", "leftrightLS"))

##let_right_ls spread is significant, will be included 

EquEUDefSpreadResults12 <- lm(EquSpendDelt ~ DefSpread_lag2 + GDPpCap + left_right_ls_spread + liberty_authority_ls_spread, EuropeDefSpread_lag2) 
summary(EquEUDefSpreadResults12)
screenreg(list(EquEUDefSpreadResults1,EquEUDefSpreadResults2, EquEUDefSpreadResults3, EquiEULeadershipResults7, EquEUDefSpreadResults11, EquEUDefSpreadResults12),
          custom.model.names=c("PubOp_df1","PubOp_df2", "PubOp_df3", "GDP", "leftrightLS", "libauthLS"))
##libauthLS isn't signficicant won't be included

EquEUDefSpreadResults13 <- lm(EquSpendDelt ~ DefSpread_lag2 + GDPpCap + left_right_ls_spread + eu_anti_pro_ls_spread, EuropeDefSpread_lag2) 
summary(EquEUDefSpreadResults13)
screenreg(list(EquEUDefSpreadResults1,EquEUDefSpreadResults2, EquEUDefSpreadResults3, EquEUDefSpreadResults7, EquEUDefSpreadResults11, EquEUDefSpreadResults13),
          custom.model.names=c("PubOp_df1","PubOp_df2", "PubOp_df3", "GDP", "leftrightLS", "euantiproLS"))
##eu anti pro isn't signficicant won't be included

```

##results 11 is final model. 

**interaction with left_right_ls_spread and Defspread**
``` {r EquSpreadInteractiontTest, echo = TRUE}

##center variables

EuropeDefSpread_lag2$left_right_ls_spreadC <- ((EuropeDefSpread_lag2$left_right_ls_spread) - mean(EuropeDefSpread_lag2$left_right_ls_spread))

EuropeDefSpread_lag2$DefSpread_lag2C <- ((EuropeDefSpread_lag2$DefSpread_lag2) - mean(EuropeDefSpread_lag2$DefSpread_lag2))

EuropeDefSpread_lag2$intrleft_right_ls_DefSread <- (EuropeDefSpread_lag2$DefSpread_lag2C * EuropeDefSpread_lag2$left_right_ls_spreadC)

EquEUDefSpreadResults14 <- lm(EquSpendDelt ~ DefSpread_lag2C + GDPpCapDelt + left_right_ls_spreadC + intrleft_right_ls_DefSread, EuropeDefSpread_lag2) 
summary(EquEUDefSpreadResults14)
screenreg(list(EquEUDefSpreadResults1,EquEUDefSpreadResults2, EquEUDefSpreadResults3, EquEUDefSpreadResults7, EquEUDefSpreadResults11, EquEUDefSpreadResults14),
          custom.model.names=c("PubOp_df1","PubOp_df2", "PubOp_df3", "GdP", "leftrightLS", "interaction"))


##interaction term is not significant and will not be used. 

```


**Tests of within and pooling** we should explain this in the 

``` {r defspreadPoolingTest, echo = TRUE}

EquEUDefSpreadResults11 <- lm(EquSpendDelt ~ DefSpread_lag2 + GDPpCapDelt left_right_ls_spread, EuropeDefSpread_lag2) 
summary(EquEUDefSpreadResults11)
screenreg(list(EquEUDefSpreadResults1,EquEUDefSpreadResults2, EquEUDefSpreadResults3, EquEUDefSpreadResults7, EquEUDefSpreadResults11),
          custom.model.names=c("PubOp_df1","PubOp_df2", "PubOp_df3", "GDPpcap", "leftrightLS"))


EquiDefSpreadPooled <- plm(EquSpendDelt ~ DefSpread_lag2 + GDPpCapDelt + left_right_ls_spread, data = EuropeDefSpread_lag2, model = "pooling")

EquiDefSpreadWithin <- plm(EquSpendDelt ~ DefSpread_lag2 + GDPpCapDelt + left_right_ls_spread, data =  EuropeDefSpread_lag2, model = "within")

pFtest(DefSpreadWithin, DefSpreadPooled)
##p = .1215  cannot reject the null that the pooling model works (all coefficients for each country should be the same ever year)

screenreg(list(EquEUDefSpreadResults11, EquiDefSpreadPooled, EquiDefSpreadWithin),
          custom.model.names = c("ols", "pooled", "within"))

##use pooled.
```
