---
title: "EUExertStrongLeadershipandDefenseSpending"
author: "src"
date: "October 19, 2015"
output: html_document
---

**Load packages and support files**
```{r Setup, echo = FALSE, results = "hide"}
options(error=recover)
options(warn=1)

require(Hmisc)
require(texreg)
require(plm)
require(ggplot2)
require(reshape)
require(plyr)
require(quantmod)

#Your working directory here!
# setwd("K:/Development/Europe") #Your working directory here!
#setwd("C:/Users/Greg Sanders/Documents/Development/Europe")
# setwd("C:/Users/scohen/My Documents/Europe/Git/Europe")

source("EuropeInput.R")

```


**Load and subset the data we want**
```{r Input, echo = FALSE, results = "hide"}


#debug(CompilePubOpDataOmnibus)
##load data using function
#undebug(CompilePubOpDataOmnibus)
EuropeOmnibus <- CompilePubOpDataOmnibus()


write.table(EuropeOmnibus
            ,file=paste("data\\EuropeOmnibus.csv"
                        ,sep=""
                        )
            #   ,header=TRUE
            , sep=","
            , row.names=FALSE
            , append=FALSE
            )


#get rid of greece
EuropeOmnibus <- subset(EuropeOmnibus, !Country %in% c("Greece", "Sweden","Russia","United States"))

##get rird of 2002 and 2003
# EuropeOmnibus <- subset(EuropeOmnibus, !Year %in% c("2002"))


write.table(EuropeOmnibus
            ,file=paste("data\\EuropeSample.csv"
                        ,sep=""
                        )
            #   ,header=TRUE
            , sep=","
            , row.names=FALSE
            , append=FALSE
            )
##change government spreads from factors



```


**load and subset the data we want**
```{r EULeadershipNarrowing, echo = TRUE, results = "hide"}

##load data using function
EULeadershipSpread <- subset(EuropeOmnibus, !is.na(EUldrSpread))


##get rid of Serbia
EULeadershipSpread <- subset(EULeadershipSpread, !Country %in% c("Serbia"))

EULeadershipSpread_lag0 <- subset(EULeadershipSpread, !is.na(EUldrSpread))
EULeadershipSpread_lag1 <- subset(EULeadershipSpread, !is.na(EUldrSpread_lag1))
EULeadershipSpread_lag2 <- subset(EULeadershipSpread, !is.na(EUldrSpread_lag2))


```

**OLS model adding each variable individually**
```{r EULeadershipspreadRegressions, echo = TRUE}
EULeadershipResults1 <- lm(DefSpendDelt ~ EUldrSpread, EULeadershipSpread_lag0) 
summary(EULeadershipResults1)
screenreg(list(EULeadershipResults1))

#lag0 on EUldrSpread is significant at the .05 level.

EULeadershipResults2 <- lm(DefSpendDelt ~ EUldrSpread_lag1, EULeadershipSpread_lag1) 
summary(EULeadershipResults2)
screenreg(list(EULeadershipResults1, EULeadershipResults2),
              custom.model.names=c("PubOp_df2","PubOp_df2"))

EULeadershipResults3 <- lm(DefSpendDelt ~ EUldrSpread_lag2, EULeadershipSpread_lag2) 
summary(EULeadershipResults3)
screenreg(list(EULeadershipResults1, EULeadershipResults3),
              custom.model.names=c("PubOp_df2","PubOp_df3"))

##lag 2 and three aren't significant

EULeadershipResults4 <- lm(DefSpendDelt ~ EUldrSpread + IntAt, EULeadershipSpread_lag0) 
summary(EULeadershipResults4)
screenreg(list(EULeadershipResults1, EULeadershipResults4),
              custom.model.names=c("PubOp_df2","IntAt"))

##not significant, IntAt won't be included.


EULeadershipResults5 <- lm(DefSpendDelt ~ EUldrSpread + CivilWar, EULeadershipSpread_lag0) 
summary(EULeadershipResults5)
screenreg(list(EULeadershipResults1, EULeadershipResults5),
              custom.model.names=c("PubOp_df2","CivilWar"))

##not si gnificant, won't be included

EULeadershipResults6 <- lm(DefSpendDelt ~ EUldrSpread + IntlCnf, EULeadershipSpread_lag0) 
summary(EULeadershipResults6)
screenreg(list(EULeadershipResults1, EULeadershipResults6),
              custom.model.names=c("PubOp_df2","IntCnf"))

##intl cnf is significant and will be included

EULeadershipResults0 <- lm(DefSpendDelt ~ EUldrSpread + IntlCnf + GDPpCapDelt, EULeadershipSpread_lag0) 
summary(EULeadershipResults0)
screenreg(list(EULeadershipResults1, EULeadershipResults6, EULeadershipResults0),
              custom.model.names=c("PubOp_df2","IntlCnf", "GDPpc"))
#GDPpc is significant and will be included 

EULeadershipResults7 <- lm(DefSpendDelt ~ EUldrSpread + IntlCnf + GDPpCapDelt + Cab_left_right, EULeadershipSpread_lag0) 
summary(EULeadershipResults7)
screenreg(list(EULeadershipResults1, EULeadershipResults6, EULeadershipResults0, EULeadershipResults7),
              custom.model.names=c("PubOp_df2", "IntlCnf", "GDPpc", "CabLeftRight"))

##cableftright not significant, won't be included

EULeadershipResults8 <- lm(DefSpendDelt ~ EUldrSpread + IntlCnf + GDPpCapDelt + Cab_liberty_authority, EULeadershipSpread_lag0) 
summary(EULeadershipResults8)
screenreg(list(EULeadershipResults1, EULeadershipResults6, EULeadershipResults0, EULeadershipResults8),
              custom.model.names=c("PubOp_df2", "IntlCnf", "GDPpc","CabLiberty_authority"))

##not significant and won't be included, cab_liberty_authority

EULeadershipResults9 <- lm(DefSpendDelt ~ EUldrSpread + IntlCnf + GDPpCapDelt + Cab_eu_anti_pro, EULeadershipSpread_lag0) 
summary(EULeadershipResults9)
screenreg(list(EULeadershipResults1, EULeadershipResults6, EULeadershipResults0, EULeadershipResults9),
              custom.model.names=c("PubOp_df2","IntlCnf", "GDPpc", "cab_eu_anti_pro"))

##cab_eu_anti_pro is not significant and wont be included

EULeadershipResults10 <- lm(DefSpendDelt ~ EUldrSpread + IntlCnf + GDPpCapDelt + left_right_ls_spread, EULeadershipSpread_lag0) 
summary(EULeadershipResults10)
screenreg(list(EULeadershipResults1, EULeadershipResults6, EULeadershipResults0, EULeadershipResults10),
              custom.model.names=c("PubOp_df2", "IntlCnf", "GDPpc", "leftrightlsspread"))

##leftrightlsspread is not significant and won't be included

EULeadershipResults11 <- lm(DefSpendDelt ~ EUldrSpread + IntlCnf + GDPpCapDelt + liberty_authority_ls_spread, EULeadershipSpread_lag0) 
summary(EULeadershipResults11)
screenreg(list(EULeadershipResults1, EULeadershipResults6, EULeadershipResults0, EULeadershipResults10),
              custom.model.names=c("PubOp_df2", "IntlCnf", "GDPpc", "libertyauthoritylsspread"))

##libertyauthority ls spread isn't significant and wont' be lincluded 

EULeadershipResults12 <- lm(DefSpendDelt ~ EUldrSpread + IntlCnf + GDPpCapDelt + eu_anti_pro_ls_spread, EULeadershipSpread_lag0) 
summary(EULeadershipResults12)
screenreg(list(EULeadershipResults1, EULeadershipResults6, EULeadershipResults0, EULeadershipResults12),
              custom.model.names=c("PubOp_df2", "IntlCnf", "GDPpc", "eu_anti_prolsspread"))

##eu_anti/pro is significant and will be included.


```

##model 12 is final

**interaction with eu_anti_pro_ls and Defspread**
``` {r EquSpreadInteractiontTest, echo = TRUE}

##center variables

EULeadershipSpread_lag0$eu_anti_pro_ls_spreadC <- ((EULeadershipSpread_lag0$eu_anti_pro_ls_spread) - mean(EULeadershipSpread$eu_anti_pro_ls_spread))

EULeadershipSpread_lag0$EUldrSpreadC <- ((EULeadershipSpread_lag0$EUldrSpread) - mean(EULeadershipSpread_lag0$EUldrSpread))

EULeadershipSpread_lag0$intreu_anti_pro_ls_EUldrSread <- (EULeadershipSpread_lag0$EUldrSpreadC * EULeadershipSpread_lag0$eu_anti_pro_ls_spreadC)

EquEUDefSpreadResults14 <- lm(DefSpendDelt ~ EUldrSpreadC + IntlCnf + GDPpCapDelt + eu_anti_pro_ls_spreadC + intreu_anti_pro_ls_EUldrSread, EULeadershipSpread_lag0) 
summary(EquEUDefSpreadResults14)
screenreg(list(EULeadershipResults1, EULeadershipResults6, EULeadershipResults0, EULeadershipResults12,EquEUDefSpreadResults14),
              custom.model.names=c("PubOp_df2", "IntlCnf", "GDPpc", "eu_anti_prolsspread","interaction"))

##interaction not significant will not be included


```


**Tests of within and pooling** we should explain this in the 

``` {r defspreadPoolingTest, echo = TRUE}

EULeadershipResults12 <- lm(DefSpendDelt ~ EUldrSpread + IntlCnf + GDPpCapDelt + eu_anti_pro_ls_spread, EULeadershipSpread_lag0) 
summary(EULeadershipResults12)
screenreg(list(EULeadershipResults1, EULeadershipResults6, EULeadershipResults0, EULeadershipResults12),
              custom.model.names=c("PubOp_df2", "IntlCnf", "GDPpc", "eu_anti_prolsspread"))


DefSpreadPooled <- plm(DefSpendDelt ~ EUldrSpread + IntlCnf + GDPpCapDelt + eu_anti_pro_ls_spread, data = EULeadershipSpread_lag0, model = "pooling")

DefSpreadWithin <- plm(DefSpendDelt ~ EUldrSpread + IntlCnf + GDPpCapDelt + eu_anti_pro_ls_spread, data =  EULeadershipSpread_lag0, model = "within")

pFtest(DefSpreadWithin, DefSpreadPooled)
##p = .168 cannot reject the null that the pooling model works (all coefficients for each country should be the same ever year)

screenreg(list(EULeadershipResults12, DefSpreadPooled, DefSpreadWithin),
          custom.model.names = c("OLS", "Pooled", "withink"))
##use pooled. 
```
