---
title: "Country spending too much or too little on defense data and defense spending"
author: "src"
date: "October 19, 2015"
output: html_document
---

**Load packages and support files**
```{r Setup, echo = FALSE, results = "hide"}
options(error=recover)
options(warn=1)

require(Hmisc)
require(texreg)
require(plm)
require(ggplot2)
require(reshape2)
require(plyr)
require(quantmod)

#Your working directory here!
# setwd("K:/Development/Europe") #Your working directory here!
# setwd("C:/Users/Greg Sanders/Documents/Development/Europe")
 setwd("C:/Users/scohen/My Documents/Europe/Git/Europe")

source("EuropeInput.R")

```


**Load and subset the data we want**
```{r Input, echo = FALSE, results = "hide"}


# debug(CompilePubOpDataOmnibus)
##load data using function
#undebug(CompilePubOpDataOmnibus)
EuropeOmnibus <- CompilePubOpDataOmnibus()


write.table(EuropeOmnibus
            ,file=paste("data\\EuropeOmnibus.csv"
                        ,sep=""
                        )
            #   ,header=TRUE
            , sep=","
            , row.names=FALSE
            , append=FALSE
            )


#get rid of greece
EuropeOmnibus <- subset(EuropeOmnibus, !Country %in% c("Greece", "Sweden","Russia","United States"))

##get rird of 2002 and 2003
# EuropeOmnibus <- subset(EuropeOmnibus, !Year %in% c("2002"))


write.table(EuropeOmnibus
            ,file=paste("data\\EuropeSample.csv"
                        ,sep=""
                        )
            #   ,header=TRUE
            , sep=","
            , row.names=FALSE
            , append=FALSE
            )
##change government spreads from factors



```


**load and subset the data we want**
```{r DefSpreadNarrowing, echo = FALSE, results = "hide"}

##load data using function
EuropeDefSpread <- subset(EuropeOmnibus, !is.na(DefSpendDelt_lead))

EuropeDefSpread <- subset(EuropeDefSpread, !is.na(DefSpread))

EuropeDefSpread <- subset(EuropeDefSpread, !Country %in% c("Serbia", "Bulgaria", "Romania", "Serbia", "Slovakia"))

EuropeDefSpread_lag0 <- subset(EuropeDefSpread, !is.na(DefSpread))
EuropeDefSpread_lag1 <- subset(EuropeDefSpread, !is.na(DefSpread_lag1))
EuropeDefSpread_lag2 <- subset(EuropeDefSpread, !is.na(DefSpread_lag2))

pdata <- plm.data(EuropeDefSpread_lag1, index=c("Country", "Year"))

```



``` {r echo = TRUE}

EUDefSpreadResults1 <- lm(DefSpendDelt_lead ~ DefSpread, EuropeDefSpread_lag0) 
screenreg(list(EUDefSpreadResults1),
          custom.model.names=c("PubOp_0"))



EUDefSpreadResults2 <- lm(DefSpendDelt_lead ~ DefSpread_lag1, EuropeDefSpread_lag1) 
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults2),
          custom.model.names=c("PubOp_0","PubOp_1"))
summary(EUDefSpreadResults2)

##lag1 is significant, will keep 

EUDefSpreadResults3 <- lm(DefSpendDelt_lead ~ DefSpread_lag2, EuropeDefSpread_lag2) 
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults2,EUDefSpreadResults3),
          custom.model.names=c("PubOp_0","PubOp_1","PubOp_2"))
summary(EUDefSpreadResults3)

##lag 2 is not significant, will not keep

EUDefSpreadResults4 <- lm(DefSpendDelt_lead ~ DefSpread_lag1 + IntAt, EuropeDefSpread_lag1)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults4),
           custom.model.names=c("PubOp_0","PubOp_1","IntAt"))
 
summary(EUDefSpreadResults4)

##don't keep intat


EUDefSpreadResults5 <- lm(DefSpendDelt_lead ~ DefSpread_lag1 + CivilWar, EuropeDefSpread_lag1)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults5),
           custom.model.names=c("PubOp_0","PubOp_1", "CivilWar"))
summary(EUDefSpreadResults5)

#don't keepcivil war



EUDefSpreadResults6 <- lm(DefSpendDelt_lead ~ DefSpread_lag1 + IntlCnf, EuropeDefSpread_lag1)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults6),
           custom.model.names=c("PubOp_0","PubOp_1", "InflConf"))
summary(EUDefSpreadResults6)

#not keeping intlcnf

# EUDefSpreadResults7 <- lm(DefSpendDelt_lead ~ DefSpread_lag2 + IntAt + CivilWar, EuropeDefSpread_lag2)
# screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults4, EUDefSpreadResults5, EUDefSpreadResults7),
#            custom.model.names=c("PubOp_0","PubOp_2","IntAt", "CivilWar", "Population"))
# summary(EUDefSpreadResults7)



EUDefSpreadResults8 <- lm(DefSpendDelt_lead ~ DefSpread_lag1 + GDPpCapDelt, EuropeDefSpread_lag1)
summary(EUDefSpreadResults8)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults8),
           custom.model.names=c("PubOp_0","PubOp_1", "GDP"))

##keep GDP

EUDefSpreadResults9 <- lm(DefSpendDelt_lead ~ DefSpread_lag1 + GDPpCapDelt + Cab_left_right, EuropeDefSpread_lag1)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults8, EUDefSpreadResults9),
           custom.model.names=c("PubOp_0","PubOp_1", "GDP", "CabLeftRight"))

##cableftright won't be included



EUDefSpreadResults10 <- lm(DefSpendDelt_lead ~ DefSpread_lag1 + GDPpCapDelt + Cab_liberty_authority, EuropeDefSpread_lag1)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults8, EUDefSpreadResults10),
           custom.model.names=c("PubOp_0","PubOp_1", "GDP", "CabLibertyAuth"))
#cablibauth wont be included



EUDefSpreadResults11 <- lm(DefSpendDelt_lead ~ DefSpread_lag1 + GDPpCapDelt + Cab_eu_anti_pro, EuropeDefSpread_lag1)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults8, EUDefSpreadResults11),
           custom.model.names=c("PubOp_0","PubOp_1", "GDP", "CabEUAntiPro"))
summary(EUDefSpreadResults11)
##won't keep cab eu anti pro

EUDefSpreadResults12 <- lm(DefSpendDelt_lead ~ DefSpread_lag1 + GDPpCapDelt + left_right_ls_spread, EuropeDefSpread_lag1)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults8, EUDefSpreadResults12),
           custom.model.names=c("PubOp_0","PubOp_1", "GDP", "left_right_lsSpread"))
summary(EUDefSpreadResults12)

##not keeping left right ls sspread

EUDefSpreadResults13 <- lm(DefSpendDelt_lead ~ DefSpread_lag1 + GDPpCapDelt + liberty_authority_ls_spread, EuropeDefSpread_lag1)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults8, EUDefSpreadResults13),
           custom.model.names=c("PubOp_0","PubOp_1", "GDP", "libertyAuth_lsSpread"))

##liberty_authority_lsspread is not significant, doesn't increase r squared and doens't affect the other veriables significantly

EUDefSpreadResults14 <- lm(DefSpendDelt_lead ~ DefSpread_lag1  + GDPpCapDelt + eu_anti_pro_ls_spread, EuropeDefSpread_lag1)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults8, EUDefSpreadResults14),
           custom.model.names=c("PubOp_0","PubOp_1", "GDP", "euAntiPro_lsSpread"))

##eu_anti_pro_ls_spread will not be included

```

##model 8 is chosen.

**Tests for panel data model.**

``` {r defspreadPoolingTest, echo = TRUE}

EUDefSpreadResults8 <- lm(DefSpendDelt_lead ~ DefSpread_lag1 + GDPpCapDelt, EuropeDefSpread_lag1)
summary(EUDefSpreadResults8)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults8),
           custom.model.names=c("PubOp_0","PubOp_1", "GDP"))


DefSpreadPooled <- plm(DefSpendDelt_lead ~ DefSpread_lag1 + GDPpCapDelt, data = pdata, model = "pooling")
summary(DefSpreadPooled)
screenreg(list(EUDefSpreadResults8, DefSpreadPooled),
          custom.model.names = c("OLS", "Pooled"))

DefSpreadBetween <- plm(DefSpendDelt_lead ~ DefSpread_lag1 + GDPpCapDelt, data = pdata, model = "between")
summary(DefSpreadBetween)
screenreg(list(EUDefSpreadResults8, DefSpreadPooled, DefSpreadBetween),
          custom.model.names = c("OLS", "Pooled", "Between"))

DefSpreadFD <- plm(DefSpendDelt_lead ~ DefSpread_lag1 + GDPpCapDelt, data = pdata, model = "fd") ##when variables don't vary from one year to the next, the variable is dropped because the first difference takes difference of the model averaged over time from the original model and for these variables the value would be 0.
screenreg(list(EUDefSpreadResults8, DefSpreadPooled, DefSpreadBetween, DefSpreadFD),
          custom.model.names = c("OLS", "Pooled", "Between", "FD"))


DefSpreadWithin <- plm(DefSpendDelt_lead ~ DefSpread_lag1 + GDPpCapDelt, data =  pdata, model = "within")
summary(DefSpreadWithin)
screenreg(list(EUDefSpreadResults8, DefSpreadPooled, DefSpreadBetween, DefSpreadFD, DefSpreadWithin),
          custom.model.names = c("OLS", "Pooled", "Between", "FD", "within"))


DefSpreadRandom <- plm(DefSpendDelt_lead ~ DefSpread_lag1 + GDPpCapDelt, data = pdata, model = "random")
screenreg(list(EUDefSpreadResults8, DefSpreadPooled, DefSpreadBetween, DefSpreadFD, DefSpreadWithin, DefSpreadRandom),
          custom.model.names = c("OLS", "Pooled", "Between", "FD", "within", "Random"))


##lagrange multiplier (lm) for random effects vs. OLS
plmtest(DefSpreadPooled) #if pvalue small, go ahead and estimate a random effects model. "alternative hypothesis, significant effects"

##fixed effects versus OLS model
pFtest(DefSpreadWithin, DefSpreadPooled)
##p = .162 cannot reject the null that the pooling model works (all coefficients for each country should be the same ever year) if p value low, supports the within model(accept alternative hypothesis: significant effects)

##hausman test for fixed versus random effects model:compares how close the coefficients of the model are:
phtest(DefSpreadRandom, DefSpreadWithin)
##small p value means one model is inconsistent, means use fixed effects model b/c that gives you consistent estimates.
```
The pooled/fixed test results in a p value of .3512 indicating that we cannot reject the null hypothesis that the pooling model works, thus we should choose the pooling model. 

##use pooled
