---
title: "European Defense and Public Opinion: Selected Models"
author: "Greg Sanders"
date: "October 19, 2015"
output: html_document
---

**Load packages and support files**
```{r Setup, echo = FALSE, results = "hide"}
options(error=recover)
options(warn=1)

require(Hmisc)
require(texreg)
require(plm)
require(ggplot2)
require(reshape2)
require(plyr)
require(quantmod)

#Your working directory here!
# setwd("K:/Development/Europe") #Your working directory here!
#setwd("C:/Users/Greg Sanders/Documents/Development/Europe")
# setwd("C:/Users/scohen/My Documents/Europe/Git/Europe")

source("EuropeInput.R")
```


**Load and subset the data we want**
```{r Input, echo = FALSE, results = "hide"}

EuropeOmnibus <- CompilePubOpDataOmnibus()
EuropeOmnibus <- subset(EuropeOmnibus, !Country %in% c("Greece", "Sweden","Russia","United States"))




panelmodels<-function(selected.formula,
                      source.data,
                      regression.name,
                      include.random=TRUE){
    
    model.df<-data.frame(name=regression.name,
        ols=I(list(lm(as.formula(selected.formula), 
                              data = source.data))),
                         between=I(list(plm(as.formula(selected.formula), 
                              data = source.data, model = "between"))),
                         fd=I(list(plm(as.formula(selected.formula), 
                              data = source.data, model = "fd"))),
                         within=I(list(plm(as.formula(selected.formula), 
                              data = source.data, model = "within"))),
                         random=I(ifelse(include.random,
                                       list(plm(as.formula(selected.formula), 
                                                  data = source.data, model = "random")),
                                       NA))
                                       
    )
    
    model.df
    
}

```



**load and subset the data we want**
```{r DefSpreadNarrowing, echo = FALSE, results = "hide"}

##load data using function
EquSpread <- subset(EuropeOmnibus, !is.na(EquSpendDelt_lead))
DefSpread <- subset(EuropeOmnibus, !is.na(DefSpendDelt_lead))

EuropeDef_model<-list()
EuropeDef_name<-c()
EuropeEqu_model<-list()
EuropeEqu_name<-c()

```


*Dependent Variable: Defense Spending*
``` {r Hyp1a_Too_Much_Little_Defense_and_Defense_Spending, echo = TRUE}




EuropeDef_model<-panelmodels(selected.formula="DefSpendDelt_lead ~ DefSpread_lag1 + GDPpCapDelt",
                              source.data=DefSpread,
                              regression.name="H1A: Too Much/Little",
                             include.random=FALSE)


summary(EuropeDef_model$ols[[1]])
summary(EuropeDef_model$between[[1]])
summary(EuropeDef_model$fd[[1]])
summary(EuropeDef_model$within[[1]])
# summary(EuropeDef_model$random[[1]])


```


``` {r Hyp1b_Too_Much_Little_Defense_and_Equipment_Spending, echo = TRUE}

EuropeEqu_model<-panelmodels(selected.formula="EquSpendDelt ~ DefSpread_lag2 + GDPpCapDelt + left_right_ls_spread",
                              source.data=DefSpread,
                              regression.name="H1B: Too Much/Little")
    
    
summary(EuropeEqu_model$ols[[1]])
summary(EuropeEqu_model$between[[1]])
summary(EuropeEqu_model$fd[[1]])
summary(EuropeEqu_model$within[[1]])
summary(EuropeEqu_model$random[[1]])


```


``` {r Hyp2a_EU_Leadership_and_Defense_Spending, echo = TRUE}

EuropeDef_model<-rbind(
    EuropeDef_model[1,],
    panelmodels(selected.formula="DefSpendDelt ~ EUldrSpread + IntlCnf + GDPpCapDelt +
                                 eu_anti_pro_ls_spread",
                source.data=DefSpread,
                regression.name="H2b: EU leader.",
                include.random=TRUE)
)

summary(EuropeDef_model$ols[[2]])
summary(EuropeDef_model$between[[2]])
summary(EuropeDef_model$fd[[2]])
summary(EuropeDef_model$within[[2]])
summary(EuropeDef_model$random[[2]])

```

``` {r Hyp2b_EU_Leadership_and_Equipment_Spending, echo = TRUE}

EuropeEqu_model<-rbind(
    EuropeEqu_model[1,],
    panelmodels(selected.formula="EquSpendDelt ~ EUldrSpread_lag1 + CivilWar + Cab_liberty_authority + Cab_eu_anti_pro",
                source.data=DefSpread,
                regression.name="H2b: EU leader.",
                include.random=FALSE)
)
    
    
summary(EuropeEqu_model$ols[[2]])
summary(EuropeEqu_model$between[[2]])
summary(EuropeEqu_model$fd[[2]]])
summary(EuropeEqu_model$within[[2]])
# summary(EuropeEqu_model$random[[2]])

```



``` {r Hyp3A, echo = TRUE}

EuropeDef_model<-rbind(
    EuropeDef_model[1:2,],
    panelmodels(selected.formula="DefSpendDelt_lead ~ NATOessSpread_lag2",
                source.data=DefSpread,
                regression.name="H3A: NATO EU Def",
                include.random=TRUE)
)

summary(EuropeDef_model$ols[[3]])
summary(EuropeDef_model$between[[3]])
summary(EuropeDef_model$fd[[3]])
summary(EuropeDef_model$within[[3]])
summary(EuropeDef_model$random[[3]])


EuropeDef_model<-rbind(
    EuropeDef_model[1:3,],
    panelmodels(selected.formula="DefSpendDelt_lead ~ NATO.EUspread_lag1  + GDPpCapDelt + liberty_authority_ls_spread",
                source.data=DefSpread,
                regression.name="H3A: NATO Ess",
                include.random=FALSE)
)

summary(EuropeDef_model$ols[[4]])
summary(EuropeDef_model$between[[4]])
summary(EuropeDef_model$fd[[4]])
summary(EuropeDef_model$within[[4]])
# summary(EuropeDef_model$random[[4]])



# screenreg(EuropeDef_model[c(1:2)],
#           custom.model.name=EuropeDef_name[c(1:2)])

```

After comparing the three options, the three year difference between expenditure and Nato Essential polling appears to have the strongest relationship, even if it no where close to significant.


``` {r Hyp3B, echo = TRUE}


EuropeEqu_model<-rbind(
    EuropeEqu_model[1:2,],
    panelmodels(selected.formula="EquSpendDelt_lead ~ NATO.EUspread_lag2  + GDPpCapDelt + eu_anti_pro_ls_spread",
                source.data=DefSpread,
                regression.name="H3B: NATO-EU",
                include.random=FALSE)
)
    
    
summary(EuropeEqu_model$ols[[3]])
summary(EuropeEqu_model$between[[3]])
summary(EuropeEqu_model$fd[[3]])
summary(EuropeEqu_model$within[[3]])
# summary(EuropeEqu_model$random[[3]])


EuropeEqu_model<-rbind(
    EuropeEqu_model[1:3,],
    panelmodels(selected.formula="EquSpendDelt_lead ~ NATOessSpread_lag1  + CivilWar",
                source.data=DefSpread,
                regression.name="H3B: NATO Ess",
                include.random=FALSE)
)

summary(EuropeEqu_model$ols[[4]])
summary(EuropeEqu_model$between[[4]])
summary(EuropeEqu_model$fd[[4]])
summary(EuropeEqu_model$within[[4]])
# summary(EuropeEqu_model$random[[4]])


# 
# screenreg(EuropeDef_model[c(1:3)],
#           custom.model.name=EuropeDef_name[c(1:3)])

```