---
title: "Untitled"
author: "src"
date: "October 19, 2015"
output: pdf_document
---

**Load packages and support files**
```{r Setup, echo = FALSE, results = "hide"}
options(error=recover)
options(warn=1)

require(Hmisc)
require(texreg)
require(plm)
require(ggplot2)
require(reshape)
require(plyr)
require(quantmod)

#Your working directory here!
# setwd("K:/Development/Europe") #Your working directory here!
#setwd("C:/Users/Greg Sanders/Documents/Development/Europe")
setwd("C:/Users/scohen/My Documents/Europe/Git/Europe")

source("EuropeInput.R")

```


**Load and subset the data we want**
```{r Input, echo = FALSE, results = "hide"}


#debug(CompilePubOpDataOmnibus)
##load data using function
#undebug(CompilePubOpDataOmnibus)
EuropeOmnibus <- CompilePubOpDataOmnibus()


write.table(EuropeOmnibus
            ,file=paste("data\\EuropeOmnibus.csv"
                        ,sep=""
                        )
            #   ,header=TRUE
            , sep=","
            , row.names=FALSE
            , append=FALSE
            )


#get rid of greece
EuropeOmnibus <- subset(EuropeOmnibus, !Country %in% c("Greece", "Sweden","Russia","United States"))

##get rird of 2002 and 2003
EuropeOmnibus <- subset(EuropeOmnibus, !Year %in% c("2002"))


write.table(EuropeOmnibus
            ,file=paste("data\\EuropeSample.csv"
                        ,sep=""
                        )
            #   ,header=TRUE
            , sep=","
            , row.names=FALSE
            , append=FALSE
            )
##change government spreads from factors



```


**load and subset the data we want**
```{r DefSpreadNarrowing, echo = FALSE, results = "hide"}

##load data using function
EuropeDefSpread <- subset(EuropeOmnibus, !is.na(DefSpendDelt_lead))

EuropeDefSpread <- subset(EuropeDefSpread, !is.na(DefSpread))

##get rid of sweden
EuropeDefSpread <- subset(EuropeDefSpread, !Country %in% c("Sweden", "Serbia", "Bulgaria", "Romania"))

EuropeDefSpread <- subset(EuropeDefSpread, !Year %in% c("2002"))


```



``` {r echo = TRUE}

EUDefSpreadResults1 <- lm(DefSpendDelt_lead ~ DefSpread, EuropeDefSpread) 
screenreg(list(EUDefSpreadResults1),
          custom.model.names=c("PubOp_df1"))



EUDefSpreadResults2 <- lm(DefSpendDelt_lead ~ DefSpread_lag1, EuropeDefSpread) 
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults2),
          custom.model.names=c("PubOp_df1","PubOp_df2"))



EUDefSpreadResults3 <- lm(DefSpendDelt_lead ~ DefSpread_lag2, EuropeDefSpread) 
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults2,EUDefSpreadResults3),
          custom.model.names=c("PubOp_df1","PubOp_df2","PubOp_df3"))



EUDefSpreadResults4 <- lm(DefSpendDelt_lead ~ DefSpread_lag2 + IntAt, EuropeDefSpread)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults4),
           custom.model.names=c("PubOp_df1","PubOp_df3","IntAt"))
 
summary(EUDefSpreadResults4)

##keep intat


EUDefSpreadResults5 <- lm(DefSpendDelt_lead ~ DefSpread_lag2 + IntAt + CivilWar, EuropeDefSpread)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults4, EUDefSpreadResults5),
           custom.model.names=c("PubOp_df1","PubOp_df3","IntAt", "CivilWar"))
summary(EUDefSpreadResults5)

##keepcivil war



EUDefSpreadResults6 <- lm(DefSpendDelt_lead ~ DefSpread_lag2 + IntAt + CivilWar + IntlCnf, EuropeDefSpread)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults4, EUDefSpreadResults5, EUDefSpreadResults6),
           custom.model.names=c("PubOp_df1","PubOp_df3","IntAt", "CivilWar", "InflConf"))
summary(EUDefSpreadResults6)

#not keeping intlcnf

EUDefSpreadResults7 <- lm(DefSpendDelt_lead ~ DefSpread_lag2 + IntAt + CivilWar + PopulationDelt, EuropeDefSpread)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults4, EUDefSpreadResults5, EUDefSpreadResults7),
           custom.model.names=c("PubOp_df1","PubOp_df3","IntAt", "CivilWar", "Population"))
summary(EUDefSpreadResults7)



EUDefSpreadResults8 <- lm(DefSpendDelt_lead ~ DefSpread_lag2 + IntAt + CivilWar + PopulationDelt + GDPpCapDelt, EuropeDefSpread)
summary(EUDefSpreadResults8)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults4, EUDefSpreadResults5, EUDefSpreadResults7, EUDefSpreadResults8),
           custom.model.names=c("PubOp_df1","PubOp_df3","IntAt", "CivilWar", "Population", "GDP"))

##Cablefright 

EUDefSpreadResults9 <- lm(DefSpendDelt_lead ~ DefSpread_lag2 + IntAt +  CivilWar + PopulationDelt + GDPpCapDelt + Cab_left_right, EuropeDefSpread)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults4, EUDefSpreadResults5, EUDefSpreadResults7, EUDefSpreadResults8, EUDefSpreadResults9),
           custom.model.names=c("PubOp_df1","PubOp_df3","IntAt", "CivilWar", "Population", "GDP", "CabLeftRight"))

##cableftright won't be included

##CabLibertyAuthority 

EUDefSpreadResults10 <- lm(DefSpendDelt_lead ~ DefSpread_lag2 + IntAt +  CivilWar + PopulationDelt + GDPpCapDelt + Cab_liberty_authority, EuropeDefSpread)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults4, EUDefSpreadResults5, EUDefSpreadResults7, EUDefSpreadResults8, EUDefSpreadResults10),
           custom.model.names=c("PubOp_df1","PubOp_df3","IntAt", "CivilWar", "Population", "GDP", "CabLibertyAuth"))
#cablibauth wont be included

##cab_eu_anti_pro 

EUDefSpreadResults11 <- lm(DefSpendDelt_lead ~ DefSpread_lag2 + IntAt +  CivilWar + PopulationDelt + GDPpCapDelt + Cab_eu_anti_pro, EuropeDefSpread)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults4, EUDefSpreadResults5, EUDefSpreadResults7, EUDefSpreadResults8, EUDefSpreadResults11),
           custom.model.names=c("PubOp_df1","PubOp_df3","IntAt", "CivilWar", "Population", "GDP", "CabEUAntiPro"))


EUDefSpreadResults12 <- lm(DefSpendDelt_lead ~ DefSpread_lag2 + IntAt +  CivilWar + PopulationDelt + GDPpCapDelt + left_right_ls_spread, EuropeDefSpread)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults4, EUDefSpreadResults5, EUDefSpreadResults7, EUDefSpreadResults8, EUDefSpreadResults12),
           custom.model.names=c("PubOp_df1","PubOp_df3","IntAt", "CivilWar", "Population", "GDP", "left_right_lsSpread"))
summary(EUDefSpreadResults12)


EUDefSpreadResults13 <- lm(DefSpendDelt_lead ~ DefSpread_lag2 + IntAt +  CivilWar + PopulationDelt + GDPpCapDelt + liberty_authority_ls_spread, EuropeDefSpread)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults4, EUDefSpreadResults5, EUDefSpreadResults7, EUDefSpreadResults8, EUDefSpreadResults13),
           custom.model.names=c("PubOp_df1","PubOp_df3","IntAt", "CivilWar", "Population", "GDP", "libertyAuth_lsSpread"))

##liberty_authority_lsspread is not significant, doesn't increase r squared and doens't affect the other veriables significantly

EUDefSpreadResults14 <- lm(DefSpendDelt_lead ~ DefSpread_lag2 + IntAt +  CivilWar + PopulationDelt + GDPpCapDelt + eu_anti_pro_ls_spread, EuropeDefSpread)
screenreg(list(EUDefSpreadResults1,EUDefSpreadResults3, EUDefSpreadResults4, EUDefSpreadResults5, EUDefSpreadResults7, EUDefSpreadResults8, EUDefSpreadResults14),
           custom.model.names=c("PubOp_df1","PubOp_df3","IntAt", "CivilWar", "Population", "GDP", "euAntiPro_lsSpread"))
summary(EUDefSpreadResults14)

```